      - name: Installazione Buildozer e P4A
        run: |
          pip install --upgrade pip
          pip install "cython<3.0.0" buildozer
          # Installiamo p4a separatamente per evitare il FileNotFoundError
          pip install git+https://github.com/kivy/python-for-android.git

      - name: Build APK
        run: |
          # Non usiamo più "clean" qui, lo lasciamo gestire a Buildozer
          buildozer -v android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"
