name: Compila APK Sicuro

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      # Usiamo un'azione specifica che ha già le dipendenze pronte
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master
